spring:
  profiles.active: local
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    enabled: false
  datasource:
    url: jdbc:mariadb://localhost:13306/ts_database?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: EVev123!@#
    hikari:
      max-lifetime: 56000
      connection-timeout: 2000
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.sql: debug
---
spring:
  config:
    activate:
      on-profile: prod
