spring:
  profiles.active: local
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents//Programming/Threesentences
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
---
spring:
  config:
    activate:
      on-profile: prod
